chapter_19_exercises/ex_19_1_blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include("users.urls")),
    path("", include("blogs.urls")),
]

chapter_19_exercises/ex_19_1_blog/blogs/urls.py
"""Defines URL patterns for the Blogs app."""

from django.urls import path

from . import views

app_name = "blogs"
urlpatterns = [
    # Main page.
    path("", views.index, name="index"),
    # Page for adding a new post.
    path("new_post/", views.new_post, name="new_post"),
    # Page for editing posts.
    path("edit_post/<int:post_id>/", views.edit_post, name="edit_post"),
]

chapter_19_exercises/ex_19_1_blog/users/urls.py
""" Define the URL patterns for users."""

from django.urls import path, include

from . import views

app_name = "users"
urlpatterns = [
    # Include default auth urls.
    path("", include("django.contrib.auth.urls")),
    # Registration page.
    path("register/", views.register, name="register"),
]

chapter_19_exercises/ex_19_1_blog/blogs/models.py
from django.db import models
from django.contrib.auth.models import User

class BlogPost(models.Model):
    """A post the user wants to share in the blog."""
    title = models.CharField(max_length=50)
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text

chapter_19_exercises/ex_19_1_blog/users/models.py
from django.db import models

# Create your models here.

chapter_19_exercises/ex_19_1_blog/blogs/forms.py
from django import forms

from .models import BlogPost

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ["title", "text"]
        labels = {"title": "Title:", "text": "Post:"}
        widgets = {"text": forms.Textarea(attrs={"cols": 40,})}

chapter_19_exercises/ex_19_1_blog/blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import BlogPost
from .forms import BlogPostForm

def index(request):
    """The main page for the Blog. Includes posts and dates."""
    posts = BlogPost.objects.order_by("-date_added")
    context = {"posts": posts}
    return render(request, "blogs/index.html", context)

@login_required
def new_post(request):
    """Add a new post."""
    if request.method != "POST":
        # No data submitted. Create a blank form.
        form = BlogPostForm()
    else:
        # POST data is submitted. Process data.
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            return redirect("blogs:index")

    # Display a blank or invalid form.
    context = {"form": form}
    return render(request, "blogs/new_post.html", context)

@login_required
def edit_post(request, post_id):
    """Edit an existing post."""
    post = BlogPost.objects.get(id=post_id)

    if post.owner != request.user:
        raise Http404

    if request.method != "POST":
        # Initial request; pre-fill the form with the current post.
        form = BlogPostForm(instance=post)
    else:
        # POST data submitted; process data.
        form = BlogPostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("blogs:index")

    context = {"post": post, "form": form}
    return render(request, "blogs/edit_post.html", context)

chapter_19_exercises/ex_19_1_blog/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register a new user."""
    if request.method != "POST":
        # Display a blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect("blogs:index")

    # Display a blank or invalid form.
    context = {"form": form}
    return render(request, "registration/register.html", context)

chapter_19_exercises/ex_19_1_blog/blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
        shrink-to-fit=no">
    <title>Blog</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery="full" %}

</head>
<body>

    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

        <a class="navbar-brand" href="{% url 'blogs:index'%}">Main Page</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">"Hello, {{ user.username }}.</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>

</body>

</html>

chapter_19_exercises/ex_19_1_blog/blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Edit post:</h2>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'blogs:edit_post' post.id %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Save Changes</button>
        {% endbuttons %}
    </form>

{% endblock content %}

chapter_19_exercises/ex_19_1_blog/blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block page_header %}
    <h2 class="display-4">Blog</h2>
    <p>The Blog keeps track of all entries showing the title,text and date
    posted.</p>
{% endblock page_header %}

{% block content %}
     <a class="btn btn-primary" href="{% url 'blogs:new_post' %}"
        role="button" style="margin-bottom: 20px">Add a new post</a>

     <h2>Posts</h2>
    {% for post in posts %}
        <div class="card mb-3">
            <h6 class="card-header">
                {{ post.title }} - {{ post.date_added|date:"M d, Y H:i" }}
                <small><a href="{% url 'blogs:edit_post' post.id %}">
                    Edit post</a></small>
            </h6>
            <div class="card-body">
                {{ post.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        <p>No posts have been added yet.</p>
    {% endfor %}

{% endblock content %}

chapter_19_exercises/ex_19_1_blog/blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{%block page_header %}
    <h2>Add a new post:</h2>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'blogs:new_post' %}" method="post" class="form">
        {% csrf_token %}
        {%bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Add post</button>
        {% endbuttons %}
    </form>

{% endblock content %}