chapter_18_exercises/ex_18_4-6-8_pizzeria/pizzas/urls.py
"""Defines URL patterns for pizzas."""

from django.urls import path

from . import views

app_name = "pizzas"
urlpatterns = [
    # Home page.
    path("", views.index, name="index"),
    # Page that shows all the pizzas.
    path("pizzas/", views.pizzas, name="pizzas"),
    # Details page for a single pizza.
    path("pizzas/<int:pizza_id>/", views.pizza, name="pizza"),
]

chapter_18_exercises/ex_18_4-6-8_pizzeria/pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("pizzas.urls")),
]

chapter_18_exercises/ex_18_4-6-8_pizzeria/pizzas/models.py
from django.db import models

from django.db import models

class Pizza(models.Model):
    """A series of pizzas available."""
    name = models.CharField(max_length=25)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name

class Topping(models.Model):
    """Ingredients to add to the Pizza."""
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name

chapter_18_exercises/ex_18_4-6-8_pizzeria/pizzas/views.py
from django.shortcuts import render

from .models import Pizza

def index(request):
    """The home page for pizzas."""
    return render(request, "pizzas/index.html")

def pizzas(request):
    """Show all pizzas."""
    pizzas = Pizza.objects.order_by("date_added")
    context = {"pizzas": pizzas}
    return render(request, "pizzas/pizzas.html", context)

def pizza(request, pizza_id):
    """Show a single pizza and all its entries."""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by("-date_added")
    context = {"pizza": pizza, "toppings": toppings}
    return render(request, "pizzas/pizza.html", context)

chapter_18_exercises/ex_18_4-6-8_pizzeria/pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Pizzeria</a> -
    <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
</p>

{% block content %}{% endblock content %}

chapter_18_exercises/ex_18_4-6-8_pizzeria/pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}
<p>This is the Pizzeria Home Page.</p>
{% endblock content %}

chapter_18_exercises/ex_18_4-6-8_pizzeria/pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block content %}

    <p>Pizza: {{ pizza }}</p>

    <p>Toppings</p>
    <ul>
    {% for topping in toppings %}
        <li>
            <p>{{ topping.name|linebreaks }}</p>
        </li>
    {% empty %}
        <li>There are no toppings for this pizza yet.</li>
    {% endfor %}
    </ul>

{% endblock content %}

chapter_18_exercises/ex_18_4-6-8_pizzeria/pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}

    <p>Pizzas</p>
    <ul>
        {% for pizza in pizzas %}
            <li>
                <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
            </li>
        {% empty %}
            <li>No pizzas have been added yet. </li>
        {% endfor %}
    </ul>

{% endblock content %}